apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: javaautoinstrumentations.java-auto-instr.sumologic.com
spec:
        #additionalPrinterColumns:
        #- JSONPath: .spec.javaOptions
        #name: Desired
        #type: string
        #- JSONPath: .status.javaOptions
        #name: Current
        #type: string
  group: java-auto-instr.sumologic.com
  names:
    kind: JavaAutoInstrumentation
    listKind: JavaAutoInstrumentationList
    plural: javaautoinstrumentations
    singular: javaautoinstrumentation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: JavaAutoInstrumentation is the Schema for the javaautoinstrumentations
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: JavaAutoInstrumentationSpec defines the desired state of
              JavaAutoInstrumentation
            type: object
            properties:
              javaOptions:
                type: string
            required:
              - javaOptions
          status:
            description: JavaAutoInstrumentationStatus defines the observed state
              of JavaAutoInstrumentation
            type: object
            properties:
              javaOptions:
                type: string
            required:
              - javaOptions
        type: object
    served: true
    storage: true
    subresources:
      status: {}
