apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-auto-instrumetation-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: java-auto-instrumetation-operator
  template:
    metadata:
      labels:
        name: java-auto-instrumetation-operator
    spec:
      serviceAccountName: java-auto-instrumetation-operator
      containers:
        - name: java-auto-instrumetation-operator
          image: sumologic/opentelemetry-collector-operator:v0.1.0
          command:
          - java-auto-instrumetation-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "java-auto-instrumetation-operator"
