kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: java-auto-instrumetation
subjects:
- kind: ServiceAccount
  name: java-auto-instrumetation
roleRef:
  kind: Role
  name: java-auto-instrumetation
  apiGroup: rbac.authorization.k8s.io
