---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      service: jaeger
  template:
    metadata:
      labels:
        service: jaeger
    spec:
      containers:
        - image: jaegertracing/all-in-one:1.17
          name: jaeger
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 14250
          resources: {}
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
      hostname: jaeger
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: "5775"
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: "6831"
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: "6832"
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: "5778"
      port: 5778
      targetPort: 5778
    - name: "9411"
      port: 9411
      targetPort: 9411
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "14268"
      port: 14268
      targetPort: 14268
    - name: "14250"
      port: 14250
      targetPort: 14250
  selector:
    service: jaeger
status:
  loadBalancer: {}
