name: OpenTelemetry Java Instrumentation JAR docker image builder

on:
  push:
    branches:
      - main

jobs:
  buildAndPublishOpenTelemetryJavaInstrumentationJarImg:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Verify changes in opentelemetry-java-instrumentation-jar directory
        uses: tj-actions/verify-changed-files@v8
        id: verify-ot-jars
        with:
          files: |
            opentelemetry-java-instrumentation-jar

      - name: Build and publish if changes observed
        if: steps.verify-ot-jars.outputs.files_changed == 'true'
        run: |
          cd opentelemetry-java-instrumentation-jar && ./image-build-and-push.sh
